In [2]:
import numpy as np
A=np.arange(100)

In [4]:
b=A[3:10]
b

array([3, 4, 5, 6, 7, 8, 9])

In [5]:
b[0]=-1200
b

array([-1200,     4,     5,     6,     7,     8,     9])

In [6]:
A

array([    0,     1,     2, -1200,     4,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24,    25,    26,
          27,    28,    29,    30,    31,    32,    33,    34,    35,
          36,    37,    38,    39,    40,    41,    42,    43,    44,
          45,    46,    47,    48,    49,    50,    51,    52,    53,
          54,    55,    56,    57,    58,    59,    60,    61,    62,
          63,    64,    65,    66,    67,    68,    69,    70,    71,
          72,    73,    74,    75,    76,    77,    78,    79,    80,
          81,    82,    83,    84,    85,    86,    87,    88,    89,
          90,    91,    92,    93,    94,    95,    96,    97,    98,
          99])

In [7]:
b=A[3:10].copy()#here b is totaly different from a the value chnaged in b is not showed in a 

In [9]:
b

array([-1200,     4,     5,     6,     7,     8,     9])

In [10]:
b[0]=12
b

array([12,  4,  5,  6,  7,  8,  9])

In [11]:

A

array([    0,     1,     2, -1200,     4,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24,    25,    26,
          27,    28,    29,    30,    31,    32,    33,    34,    35,
          36,    37,    38,    39,    40,    41,    42,    43,    44,
          45,    46,    47,    48,    49,    50,    51,    52,    53,
          54,    55,    56,    57,    58,    59,    60,    61,    62,
          63,    64,    65,    66,    67,    68,    69,    70,    71,
          72,    73,    74,    75,    76,    77,    78,    79,    80,
          81,    82,    83,    84,    85,    86,    87,    88,    89,
          90,    91,    92,    93,    94,    95,    96,    97,    98,
          99])

In [12]:
A[::5]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [13]:
A[::-5]

array([99, 94, 89, 84, 79, 74, 69, 64, 59, 54, 49, 44, 39, 34, 29, 24, 19,
       14,  9,  4])

In [14]:
A[::1]
A

array([    0,     1,     2, -1200,     4,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24,    25,    26,
          27,    28,    29,    30,    31,    32,    33,    34,    35,
          36,    37,    38,    39,    40,    41,    42,    43,    44,
          45,    46,    47,    48,    49,    50,    51,    52,    53,
          54,    55,    56,    57,    58,    59,    60,    61,    62,
          63,    64,    65,    66,    67,    68,    69,    70,    71,
          72,    73,    74,    75,    76,    77,    78,    79,    80,
          81,    82,    83,    84,    85,    86,    87,    88,    89,
          90,    91,    92,    93,    94,    95,    96,    97,    98,
          99])

In [15]:
idx=np.argwhere(A==-1200)[0][0]

In [16]:

idx

3

In [17]:
A=np.round(10*np.random.rand(5,4))

In [18]:
A

array([[9., 9., 0., 4.],
       [9., 5., 9., 9.],
       [9., 5., 1., 9.],
       [7., 7., 7., 0.],
       [5., 1., 1., 4.]])

In [20]:
A[1,1]

5.0

In [21]:
A[1,:]

array([9., 5., 9., 9.])

In [22]:
A[:,3]

array([4., 9., 9., 0., 4.])

In [23]:
A[1:3,2:4]

array([[9., 9.],
       [1., 9.]])

In [24]:
A.T

array([[9., 9., 9., 7., 5.],
       [9., 5., 5., 7., 1.],
       [0., 9., 1., 7., 1.],
       [4., 9., 9., 0., 4.]])

In [25]:
import numpy.linalg as la

In [27]:
la.det(np.random.rand(3,3))

0.05938750023293816

In [28]:
A

array([[9., 9., 0., 4.],
       [9., 5., 9., 9.],
       [9., 5., 1., 9.],
       [7., 7., 7., 0.],
       [5., 1., 1., 4.]])

In [29]:
A.sort(axis=1)

In [30]:
A

array([[0., 4., 9., 9.],
       [5., 9., 9., 9.],
       [1., 5., 9., 9.],
       [0., 7., 7., 7.],
       [1., 1., 4., 5.]])

In [1]:
import numpy as np


In [4]:
w=np.array([1.0,2.5,-3.3])
b=4
x=np.array([10,20,30])
n=3

In [5]:
f=0
for i in range(0,n):
    f=f+w[i]+x[i];
f=f+b

In [6]:
print(f)

64.2


In [7]:
a=np.arange(10)
print (a)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
c=a[2:7:1]
c

array([2, 3, 4, 5, 6])

In [9]:
c=a[3:]

In [10]:
c

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
a=np.array([1,2,3,4])
b=np.sum(a)
c=np.mean(a)
d=a**2
b


10

In [14]:
c

2.5

In [15]:
d

array([ 1,  4,  9, 16])

In [16]:
#vector vector element wise operation
a=np.array([1,2,3,4])
b=np.array([-1,-2,-3,-4])
b-a

array([-2, -4, -6, -8])

In [17]:
b+a

array([0, 0, 0, 0])

In [18]:
c = np.array([1, 2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)

The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


In [19]:
def my_dot(a,b):
    x=0
    for i in range(a.shape[0]):
        x=x+a[i]+b[i]
    return x
    

In [23]:
a=np.array([1,2,3,4])
b=np.array([-1,4,3,2])
print(my_dot(a,b))

18


In [26]:
a=np.array([2,3,4,5])
b=np.array([-1,6,7,8])
c=np.dot(a,b)
c
c.shape

()

In [27]:
import copy, math
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('./deeplearning.mplstyle')
np.set_printoptions(precision=2)  # reduced display precision on numpy arrays

TypeError: the 'package' argument is required to perform a relative import for './deeplearning'